### ISSUE TITLE
Build distributes the distribution-packages under the file structure of the code.

### ISSUE THREAD

**Issue by leo42** [Anastasia-Labs/lucid-evolution#140]
Build distributes the distribution-packages under the file structure of the code. 

This makes is exceptionally hard to quickly build a new version of lucid-evolution and test against them by replacing lucid-evolution node-module files with ones you just created. 

Am I missing something ?  maybe a script that organizes and gives you the binaries in a way you can use them immediately ?

**Comment by solidsnakedev** [comment]
Every package in our repository has its own `package.json` file, which includes build scripts. You can either run `pnpm build` from the root folder to build all packages, or navigate to a specific package directory, like packages/lucid, and run `pnpm build` there.

For quick compiled version for testing, you can use the following commands inside the packages/lucid directory:
`pnpm build & pnpm pack`

This will generate a compiled version that you can use to test against any project you have. Additionally, if you want to test specific functionality, you can create a test file inside the test folder. You can find the test folder here: https://github.com/Anastasia-Labs/lucid-evolution/tree/main/packages/lucid/test

**Comment by leo42** [comment]
pnpm pack that's the magic word I was looking for. Thank you!

**Comment by leo42** [comment]
@solidsnakedev  can you point me in the direction of some instructions on how to pack and load lucid-evolution from code into a npm project ( I need to test in the browser ) 

Ps. I would love some feed back on my q in https://github.com/Anastasia-Labs/lucid-evolution/pull/139

**Comment by solidsnakedev** [comment]
if you want to install the official package, you can go to https://www.npmjs.com/package/@lucid-evolution/lucid , otherwise if you want to install your own custom version, follow the instructions mentioned above

**Comment by leo42** [comment]
> if you want to install the official package, you can go to https://www.npmjs.com/package/@lucid-evolution/lucid , otherwise if you want to install your own custom version, follow the instructions mentioned above

Yes, i pnpm pack (after some fixes to to package.json) now I have a zip file of lucid evolution. How do I then import that package into another pnpm or npm project ?

I am trying to contribute here installing the official package will not really help....

**Comment by nikhils9** [comment]
Once you have the tarball (`*.tgz`) file, you can copy it to the root folder of any pnpm project and specify it as a dependency like:
```
"dependencies": {
    "@lucid-evolution/lucid": "file:file_name.tgz",
  }
```
Doing a `pnpm install` afterwards and you are good to use it.
