### ISSUE TITLE
WASM Error: Memory access out of bounds

### ISSUE THREAD

**Issue by nikhils9** [Anastasia-Labs/lucid-evolution#149]
Complete error:
```
RuntimeError: memory access out of bounds
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:670612
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2248216
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2240349
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2237935
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2189441
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2491805
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2213847
 ❯ ../../node_modules/.pnpm/@dcspark+cardano-multiplatform-lib-nodejs@5.3.0/node_modules/@dcspark/cardano-multiplatform-lib-nodejs/cardano_multiplatform_lib.js:19117:79
```

Accompanying error:
```
Error: recursive use of an object detected which would lead to unsafe aliasing in rust
 ❯ module.exports.__wbindgen_throw ../../node_modules/.pnpm/@dcspark+cardano-multiplatform-lib-nodejs@5.3.0/node_modules/@dcspark/cardano-multiplatform-lib-nodejs/cardano_multiplatform_lib.js:37518:11
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2501206
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2501220
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2211768
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:1633196
 ❯ null.<anonymous> wasm:/wasm/00a747c2:1:2180248
 ❯ ../../node_modules/.pnpm/@dcspark+cardano-multiplatform-lib-nodejs@5.3.0/node_modules/@dcspark/cardano-multiplatform-lib-nodejs/cardano_multiplatform_lib.js:11775:77
```

So far this error has been observed to occur after successfully submitting a transaction using the Staking Validator design pattern (multiple script inputs being spent along with a withdrawal). The transaction gets successfully confirmed too every time. A reproduction has been added as a test in branch [fix/memory-access-out-of-bounds](https://github.com/Anastasia-Labs/lucid-evolution/blob/fix/memory-access-out-of-bounds/packages/lucid/test/onchain.test.ts#L30). 
Once such failed test [run](https://github.com/Anastasia-Labs/lucid-evolution/actions/runs/9546244316/job/26308686470?pr=148#step:10:89)

Attaching code snippets for source of these errors in `cardano_multiplatform_lib.js`:
- Line  11775: `const Ed25519KeyHashListFinalization = new FinalizationRegistry(ptr => wasm.__wbg_ed25519keyhashlist_free(ptr));`
- Line  19117: `const PartialPlutusWitnessFinalization = new FinalizationRegistry(ptr => wasm.__wbg_partialplutuswitness_free(ptr));`
- Line  37491: `const WithdrawalBuilderResultFinalization = new FinalizationRegistry(ptr => wasm.__wbg_withdrawalbuilderresult_free(ptr));`

**Comment by kunj77** [comment]
I have encountered the same issue. Here's the log
`RuntimeError: memory access out of bounds

  RuntimeError: memory access out of bounds
      at wasm://wasm/00a7830e:wasm-function[611]:0xea2bb
      at wasm://wasm/00a7830e:wasm-function[2[73](https://github.com/MynthAI/mynth-swaps/pull/121/checks#step:7:74)]:0xa40bc
      at wasm://wasm/00a7830e:wasm-function[2409]:0x18fa81
      at wasm://wasm/00a7830e:wasm-function[5312]:0x21532b
      at /home/runner/work/mynth-swaps/mynth-swaps/packages/mynth-swaps/node_modules/@dcspark/cardano-multiplatform-lib-nodejs/cardano_multiplatform_lib.js:117[75](https://github.com/MynthAI/mynth-swaps/pull/121/checks#step:7:76):77
      at FinalizationRegistry.cleanupSome (<anonymous>)`
      
This happens when I run a more than 3 tests cases which are doing transactions using smart contracts and chaining. If I run the tests in batches of 3 all of them pass, however, if I run all together I get this error for 4th or 5th test. Am concerned in the real world we might start facing this issue when we have actual users. Can you please look into this?

**Comment by solidsnakedev** [comment]
@nikhils9 try the new version

**Comment by nikhils9** [comment]
The latest version `0.2.45` fixes this issue. Successful test [run](https://github.com/Anastasia-Labs/lucid-evolution/actions/runs/9661892219/job/26650591905)
