### ISSUE TITLE
OverrideUtxos for wallet created makeWalletFromAddress

### ISSUE THREAD

**Issue by kunj77** [Anastasia-Labs/lucid-evolution#161]
Hi, I see that overrideUtxos for a makeWalletFromAddress has a TODO. Is there a plan to implement this function or do we need to create the wallet using new utxos before every transaction while chaining?

**Comment by solidsnakedev** [comment]
Yes we’re planning to do it, we’re a bit tight with other things, but we’ll work on it soon

**Comment by solidsnakedev** [comment]
fixed https://github.com/Anastasia-Labs/lucid-evolution/pull/178
