### ISSUE TITLE
Attempting to pay to an address with an empty assets object

### ISSUE THREAD

**Issue by kunj77** [Anastasia-Labs/lucid-evolution#162]
Hi, I am trying to use pay.ToAddress but without any assets for a transaction
`lucid
    .newTx()
    .pay.ToAddressWithData(
      address,
      {
        kind: "inline",
        value: Data.void(),
      },
      {},
      validator,
    )`
    
This was allowed in lucid-cardano, but I get an error `Attempting to pay to an address with an empty assets object` with lucid-evolution. Can you guys support this? Currently we having to add additional ada while doing this just to satisfy the condition

**Comment by solidsnakedev** [comment]
You can set it to undefined, but we could add an empty object as well

**Comment by kunj77** [comment]
Thanks, it works
