### ISSUE TITLE
Unable to submit transaction

### ISSUE THREAD

**Issue by kunj77** [Anastasia-Labs/lucid-evolution#171]
Am trying to submit a transaction using sign.withPrivateKey. If I only transfer assets then it submits correctly. However, if I withdrawing using a redeemer then I get an error saying "MissingVKeyWitnessesUTXOW" for the same key. Am using chained transactions. However, if I take the cbor the same transaction(with redeemer thats failing programatically) and submit it directly via Eternl wallet then it succeeds. 

Can you please look into it? I need to be able to the submit the transaction programatically.

**Comment by kunj77** [comment]
I found that the problem is occurring due to `addSigner(<stake-key>)`. For our validator we need to add stake key as the signer, if we do that it fails. Here's a small script for the same

`const run = async (params: Params) => {
  const wallet = new Seed(seed, "testnet");
  const key = wallet.getPrivateKey();
  const skey = getStakeKey(wallet.getAddress());
  const lucid = (await params.lucid.fromAddress(wallet.getAddress())).assert();
  const provider = lucid.config().provider;
  const script = (
    await lucid.utxosByOutRef([{ txHash: scriptRef, outputIndex: 0 }])
  )[0];
  if (!script.scriptRef) throw new Error("Invalid script");

  const address = validatorToRewardAddress("Preview", script.scriptRef);
  const tx = lucid
    .newTx()
    .withdraw(address, 0n, Data.void())
    .readFrom([script])
    .addSigner(skey)
  const completed = await tx.complete();
  const signed = await completed.sign.withPrivateKey(key).complete();

  const hash = await provider.submitTx(signed.toCBOR());
  console.info("Submitted", hash);
};`

In here if I use addSigner(wallet.getAddress()) it submits successfully but fails if its with stake key

**Comment by SynthLuvr** [comment]
What could be useful is a `signWithSeed` method that can sign with both the payment key _and_ stake key

**Comment by nikhils9** [comment]
Closing this in favor of #265
