### ISSUE TITLE
`toString` like function to serialise built transaction skeleton

### ISSUE THREAD

**Issue by sourabhxyz** [Anastasia-Labs/lucid-evolution#188]
Lucid had [`toString`](https://github.com/spacebudz/lucid/blob/457c156e74ef49ce35823aa2bca91b3bbc585221/src/lucid/tx.ts#L616) function which one could use to serialise built transaction skeleton and diagnose it (without requiring to peek into library internals as known CDDL specification is followed).
While doing [migration](https://github.com/geniusyield/dex-lucid/pull/5) to lucid-evolution, I am getting script failures and am not sure how to go about debugging it. It appears the field of interest is [`txBuilder`](https://github.com/Anastasia-Labs/lucid-evolution/blob/8d6c91081415c8d9b92c203be42a6838316f962b/packages/lucid/src/tx-builder/TxBuilder.ts#L36) but am not sure how to pretty print it, printing it from config just gives some pointer value.

**Comment by solidsnakedev** [comment]
I see so you want the serialized builder before `complete()` , will work on it
