### ISSUE TITLE
Migration guide from Lucid?

### ISSUE THREAD

**Issue by sourabhxyz** [Anastasia-Labs/lucid-evolution#189]
Is there such a guide? I think it would in general be useful for easy adoption of `@lucid-evolution/lucid` from `lucid-cardano`.

**Comment by cmorgado** [comment]
The migration is quite simple.
start by changing the import and then in VS Code you get the suggestions for other dependencies, and with the documentation is quite fast

**Comment by sourabhxyz** [comment]
@cmorgado Thanks for chiming! I did somewhat that, but I am suddenly receiving script failures in my tests: https://github.com/geniusyield/dex-lucid/pull/5/files.

**Comment by sourabhxyz** [comment]
> You need to change more:
simple things like
.payToAddressWithData to
.payTo.AddressWithData
the addSignerKey
now you just need addSigner(address of signer)

And that's exactly what is done in the shared pr...

**Comment by cmorgado** [comment]
Sorry did not saw that.
On my side I'm only having trouble using the npm version and bundling with
webpack :(


Best regards
Cristóvão Morgado
pt.linkedin.com/in/cmmorgado/
github.com/cmorgado

   -




Sourabh ***@***.***> escreveu (quinta, 8/08/2024 à(s) 13:34):

**Comment by solidsnakedev** [comment]
this should help, https://anastasia-labs.github.io/lucid-evolution
what's the script failure?

**Comment by sourabhxyz** [comment]
@solidsnakedev Failure was due to [this](https://github.com/Anastasia-Labs/lucid-evolution/issues/227) bug in lucid-evolution. I no longer see script failures if inline datum is employed.

**Comment by sourabhxyz** [comment]
Perhaps shared guide, https://anastasia-labs.github.io/lucid-evolution (worth mentioning it in the readme file), is enough and dedicated migration guide is not needed. Feel free to close this issue.
