### ISSUE TITLE
using lucid-evolution in browser environment

### ISSUE THREAD

**Issue by cmorgado** [Anastasia-Labs/lucid-evolution#192]
In order to package the source code using webpack there is the need to add the following configuration

` resolve: {
     fallback: { crypto: false },
 }`

otherwise bundling will fail

![image](https://github.com/user-attachments/assets/fba62d06-4507-49d2-9437-acf1b01b992d)

**Comment by solidsnakedev** [comment]
fixed https://github.com/Anastasia-Labs/lucid-evolution/pull/208
