### ISSUE TITLE
wasm files not being loaded- lucid/blockfrost + Next.js

### ISSUE THREAD

**Issue by brian-atriumlab** [Anastasia-Labs/lucid-evolution#194]
When using Lucid with a Next.js browser project, wasm files within the @lucid-evolution/lucid module don't seem to be getting loaded as needed.

When initializing lucid w/ blockfrost in a NextJS/React application, lucid fails to load:
`TypeError: wasm.costmodels_new is not a function at ConstModels.new (cardano_multiplatform_lib_bg.js:11060:26)`

Reproducible in this repo/demo project: https://github.com/brian-atriumlab/lucid-evolution-next

**Comment by solidsnakedev** [comment]
working example https://github.com/solidsnakedev/elemt-frontend

**Comment by solidsnakedev** [comment]
fixed https://github.com/Anastasia-Labs/lucid-evolution/pull/211
