### ISSUE TITLE
Some transactions fail on Trezor

### ISSUE THREAD

**Issue by SynthLuvr** [Anastasia-Labs/lucid-evolution#196]
![image](https://github.com/user-attachments/assets/a514a0a7-ff67-4763-941c-ce8583d855a6)

It's believed this is caused because lucid-evolution doesn't conform to [CIP-21](https://cips.cardano.org/cip/CIP-21), specifically:
> The keys in every map must be sorted from lowest value to highest.

**Comment by SynthLuvr** [comment]
Confirmed that if transactions are transformed via [cardano-hw-cli](https://github.com/vacuumlabs/cardano-hw-cli?tab=readme-ov-file#transform-transaction), then they work.

It is due to lucid-evolution not conforming to CIP-21. The workaround I have:

1. Build transaction via lucid-evolution
2. Complete tx with empty signature
3. Convert to CBOR
4. Transform CBOR via `cardano-hw-cli`
5. Pass transformed CBOR back into lucid via `fromTx`
6. Continue as per usual

**Comment by solidsnakedev** [comment]
Thanks for the report will look into it

**Comment by SynthLuvr** [comment]
Beginning with lucid-evolution 0.3.10, due to #228, transactions with datums are no longer compatible with `cardano-hw-cli`. This means that lucid-evolution is now mostly unusable with some hardware wallets

**Comment by SynthLuvr** [comment]
The transformation by `cardano-hw-cli` is successful, but the produced CBOR is invalid:
```
Transaction::from_bytes: Deserialization failed in Transaction.witness_set.TransactionWitnessSet.plutus_datums.NonemptySet.PlutusData.ConstrPlutusData.ConstrPlutusData.fields.PlutusData.Bytes because: Out of range: 203 - must be in range 0 - 64
```
Opened https://github.com/vacuumlabs/cardano-hw-cli/issues/179

**Comment by solidsnakedev** [comment]
I added canonical format, https://github.com/Anastasia-Labs/lucid-evolution/pull/333/files
