### ISSUE TITLE
Add new Conway certificates

### ISSUE THREAD

**Issue by solidsnakedev** [Anastasia-Labs/lucid-evolution#219]
- [ ] CML.Certificate.new_reg_drep_cert
- [ ] CML.Certificate.new_unreg_drep_cert
- [ ] CML.Certificate.new_update_drep_cert
- [ ] CML.Certificate.new_resign_committee_cold_cert
- [ ] CML.Certificate.new_auth_committee_hot_cert
- [ ] CML.Certificate.new_stake_vote_deleg_cert
- [ ] CML.Certificate.new_vote_deleg_cert
- [ ] CML.Certificate.new_vote_reg_deleg_cert
- [ ] CML.Certificate.new_stake_vote_reg_deleg_cert
- [ ] CML.Certificate.new_stake_reg_deleg_cert

Take one task at least, and update in the comments

**Comment by hadelive** [comment]
https://github.com/Anastasia-Labs/lucid-evolution/pull/308
https://github.com/Anastasia-Labs/lucid-evolution/pull/312
