### ISSUE TITLE
Tx Submission Fails with Emulator

### ISSUE THREAD

**Issue by keyan-m** [Anastasia-Labs/lucid-evolution#257]
## The Problem

Using `Emulator` as the provider leads to failed transaction submissions.

## How to Reproduce

Checkout [this commit of `smart-handles-offchain`](https://github.com/Anastasia-Labs/smart-handles-offchain/commit/7f75d1b1fc43f1cf4808ba995e795d262d9ba751) and run its tests. Transaction submissions fail with an empty log ([`[Object]` is empty](https://github.com/Anastasia-Labs/smart-handles-offchain/actions/runs/10542620655/job/29209606758#step:8:70)):
![image](https://github.com/user-attachments/assets/54609fae-77f2-4bd4-98d2-8c759a9a70d1)

**Comment by hadelive** [comment]
You should prepare the emulator UTxOs for the transaction.
