### ISSUE TITLE
CBOR decode error

### ISSUE THREAD

**Issue by ariady-putra** [Anastasia-Labs/lucid-evolution#270]
Hey Anastasia Labs,

I'm converting an old pilot project from Lucid to Lucid-Evolution, one of my scripts accepts an [OutputReference](https://aiken-lang.github.io/stdlib/aiken/transaction.html#OutputReference) as a parameter. It used to work, but now it says:
```
Error: CBOR decode error: too many terminals, data makes no sense
    at decode (decode.js:214:11)
    at applyParamsToScript (index.js:281:126)
    at mint (App.tsx:249:50)
```

Here's the piece of code:
```node
const utxo = utxos[0];
const txHash = new Constr(0, [String(utxo.txHash)]);
const outputIndex = BigInt(utxo.outputIndex);
const oRef = new Constr(0, [txHash, outputIndex]);
console.log(oRef); // just for debugging, see screenshots below

const mintingScript = applyParamsToScript(SmartContract.mint, [oRef]);
```
| Old Lucid | Lucid-Evolution |
|-----------|-----------------|
|![Screenshot from 2024-08-30 09-38-12](https://github.com/user-attachments/assets/93883d40-509c-4bde-a2cb-53cef0fd3621)|![Screenshot from 2024-08-30 09-38-06](https://github.com/user-attachments/assets/037fb7c1-88c0-4d78-a62f-1a4f3a27600d)|

Here's the link to the project pointing to the exact lines: https://github.com/cdev-meetup/hello_aiken/commit/d65786ee0cad04481ea44856a488a845da5eee62?diff=split&w=1#diff-064c004256271ebb3efdfbf40de444479524a611c56ba9b63b14af2b7f52d94dR246-R252

Libraries version used:
```json
"@lucid-evolution/core-types": "^0.1.14",
"@lucid-evolution/core-utils": "^0.1.13",
"@lucid-evolution/lucid": "^0.3.16",
"@lucid-evolution/provider": "^0.1.45",
```
👉 the whole [package.json](https://github.com/cdev-meetup/hello_aiken/blob/lucid-evolution/offchain/package.json)

If you have examples on more complex script parameters than https://anastasia-labs.github.io/lucid-evolution/documentation/deep-dives/smart-contract-interactions#apply-parameters I'll appreciate it, thank you.

Warm regards,
Ariady

**Comment by solidsnakedev** [comment]
Make sure  to use the `applyDoubleCborEncoding` function before applying the parameter.
```typescript
const mintingScript = applyParamsToScript(applyDoubleCborEncoding(SmartContract.mint), [oRef]);
```
can you add a note? @0xBora

**Comment by ariady-putra** [comment]
> ```ts
> applyDoubleCborEncoding
> ```

Hey, yes it works. Thanks! But now there's an unrelated error when about to submitting a tx, I'll just send a message on Discord

**Comment by colll78** [comment]
Also note that if you are using `PlutusV3`, the `BuiltinData` representation of `TxOutRef` has changed from:
```
Constr 0 [ Constr 0 [txHash], outputIndex] 
```
To
```
Constr 0 [ txHash, outputIndex] 
```

This is because the `BuiltinData` representation of `TxId` changed from `Constr 0 [txHashBytes]` to `txHashBytes` (is now just a `BuiltinByteString`)

**Comment by ariady-putra** [comment]
> Also note that if you are using `PlutusV3`, the `BuiltinData` representation of `TxOutRef` has changed from:
> ```
> Constr 0 [ Constr 0 [txHash], outputIndex] 
> ```
> To
> ```
> Constr 0 [ txHash, outputIndex] 
> ```
> 
> This is because the `BuiltinData` representation of `TxId` changed from `Constr 0 [txHashBytes]` to `txHashBytes` (is now just a `BuiltinByteString`).
> 
> So the parameter that you would apply to a PlutusV3 script would instead be:
> ```
> const utxo = utxos[0];
> const txHash = String(utxo.txHash);
> const outputIndex = BigInt(utxo.outputIndex);
> const oRef = new Constr(0, [txHash, outputIndex]);
> ```

Hey thanks Phil, the issue has been resolved. It was my mistake 😁
Long time no see. Idk if you remember me or not, I'm one of your students back in Dapp360

**Comment by colll78** [comment]
> > Also note that if you are using `PlutusV3`, the `BuiltinData` representation of `TxOutRef` has changed from:
> > ```
> > Constr 0 [ Constr 0 [txHash], outputIndex] 
> > ```
> > To
> > ```
> > Constr 0 [ txHash, outputIndex] 
> > ```
> > 
> > This is because the `BuiltinData` representation of `TxId` changed from `Constr 0 [txHashBytes]` to `txHashBytes` (is now just a `BuiltinByteString`).
> > 
> > So the parameter that you would apply to a PlutusV3 script would instead be:
> > ```
> > const utxo = utxos[0];
> > const txHash = String(utxo.txHash);
> > const outputIndex = BigInt(utxo.outputIndex);
> > const oRef = new Constr(0, [txHash, outputIndex]);
> > ```
> 
> Hey thanks Phil, the issue has been resolved. It was my mistake 😁
> Long time no see. Idk if you remember me or not, I'm one of your students back in Dapp360

Yes I remember! Really happy to see that you're still involved in the ecosystem and developing on Cardano!
