### ISSUE TITLE
Fix `TxBuilder.compose()`

### ISSUE THREAD

**Issue by nikhils9** [Anastasia-Labs/lucid-evolution#277]
`compose` [currently](https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/src/tx-builder/TxBuilder.ts#L294) just tries to add up `programs` of two `TxBuilderConfig`, however for tx building, coin selection, chaining etc to work correctly the entire state of `TxBuilderConfig` needs to be carefully merged (no duplicate utxos/ scripts, appropriate min fee if both have set etc)

```ts
export type TxBuilderConfig = {
  readonly lucidConfig: LucidConfig;
  readonly txBuilder: CML.TransactionBuilder;
  walletInputs: UTxO[];
  collectedInputs: UTxO[];
  readInputs: UTxO[];
  consumedInputs: UTxO[];
  totalOutputAssets: Assets;
  mintedAssets: Assets;
  scripts: Map<string, { type: ScriptType; script: string }>;
  programs: Effect.Effect<void, TransactionError, never>[];
  partialPrograms: Map<
    RedeemerBuilder,
    (redeemer?: string) => Effect.Effect<void, TransactionError, never>
  >;
  minFee: bigint | undefined;
};
```

**Comment by solidsnakedev** [comment]
I'm not in favour of keeping compose, having mutable object is way too time consuming to maintain.
We should stay away from it as much as possible.

**Comment by nikhils9** [comment]
I agree, maintaining it would be quite cumbersome. Although, letting go of `compose` would be quite a loss. It leads to quite clean and elegant conditional tx building. I will try to think of a implementation which can facilitate similar conditional tx building but with just a single state (`TxBuilderConfig`).

**Comment by thanhvh2205** [comment]
`TxBuilder.compose` is currently not functioning as expected. I ran a basic test to compose two TxBuilders, but the result only included the first TxBuilder instead of both.

**Comment by leo42** [comment]
Same issue, compose is not operating as expected, its basically not composing. 

Just throwing my 2 cents, compose not only creates cleaner code but I have also needed it for composability scenarios, where I create a minimal tx for a smart or multiset wallet and then compose it with a defi transaction I get from something like the minswap SDK

**Comment by kylixafonso** [comment]
We at Liqwid Labs use `Tx.compose` in 90% of our transaction workflow code, so it'd be amazing if you could maintain this functionality.
