### ISSUE TITLE
Redeemer can be `null`

### ISSUE THREAD

**Issue by thanhvh2205** [Anastasia-Labs/lucid-evolution#297]
As an [interface](https://github.com/Anastasia-Labs/lucid-evolution/blob/97d31543b667fab1cc82f489630447a5f27f0826/packages/lucid/src/tx-builder/internal/Stake.ts#L140) of function, `Redeemer` can be null, but the function consistently returns [`MISSING_REDEEMER`](https://github.com/Anastasia-Labs/lucid-evolution/blob/97d31543b667fab1cc82f489630447a5f27f0826/packages/lucid/src/tx-builder/internal/Stake.ts#L187)

**Comment by solidsnakedev** [comment]
Redeemer can be null when the withdraw stake credential is a pubkey hash, not a script hash
