### ISSUE TITLE
Stake withdrawal encoding changed

### ISSUE THREAD

**Issue by SynthLuvr** [Anastasia-Labs/lucid-evolution#311]
```ts
.withdraw(address, 0n, Data.void())
```
Prior to v0.3.20, the script purpose was encoded as:
```
121([_ 122([_ h\'524A8B6C686BF0C225C8BC8EB63100BDF1047A35599626878EDF3BFE\'])])
```
Since v0.3.22, the script purpose is encoded as:
```
122([_ h\'524A8B6C686BF0C225C8BC8EB63100BDF1047A35599626878EDF3BFE\'])
```
This is causing errors interacting with existing Plutus v2 scripts.

**Comment by hadelive** [comment]
closed https://preprod.cexplorer.io/tx/9b2695cb4d2e4c0389c8fc7682bf25503efe8fe3fe3c3c97cd54e837ba005d8e

**Comment by SynthLuvr** [comment]
Downgrading to `@lucid-evolution/uplc` to 0.2.11 resolves the issue

**Comment by hadelive** [comment]
https://github.com/aiken-lang/aiken/pull/997/files#diff-3290b6fe81a878e8c43939136da0485aa2734d2a25c06c61dd0176bbe1666f02L353-L362

**Comment by SynthLuvr** [comment]
Confirmed fixed
