### ISSUE TITLE
Expose Outputs of a Partially Built Transaction

### ISSUE THREAD

**Issue by keyan-m** [Anastasia-Labs/lucid-evolution#329]
Currently `.config()` method of a `TxBuilder` exposes some pieces of information about the state, such as `collectedInputs`, `consumedInputs` (are these two identical by the way?), `totalOutputAssets`, etc., but there is no property such as `producedOutputs`.

Having access to the outputs alleviates any need for keeping an external record.

**Comment by solidsnakedev** [comment]
will go with this approach, https://github.com/Anastasia-Labs/lucid-evolution/issues/188
