### ISSUE TITLE
[Bug] Not found reference script in UTxO after build tx with toAddressWithData

### ISSUE THREAD

**Issue by Mavis2103** [Anastasia-Labs/lucid-evolution#375]
`tx.collectFrom([fundUtxo]).pay.ToAddressWithData(
        ownAddr,
        {
          kind: "inline",
          value: datum ?? Data.void()
        },
        {
        },
        script
      )
      `
https://preview.cardanoscan.io/transaction/8665bcd1586fbf524b36ffd52777dddc7e91015290b1ef70649b8f8f021dc99f?tab=utxo
"@lucid-evolution/lucid": "^0.3.51
I am building a transaction with scriptRef but the returned results do not have scriptRef even though I have checked that there is a "script" log.

**Comment by hadelive** [comment]
Try https://preview.cexplorer.io/tx/8665bcd1586fbf524b36ffd52777dddc7e91015290b1ef70649b8f8f021dc99f
