### ISSUE TITLE
setCollateral default is not enough for some transactions

### ISSUE THREAD

**Issue by a-osiecki** [Anastasia-Labs/lucid-evolution#393]
The setCollateral value of 5 ADA set here:
[https://github.com/Anastasia-Labs/lucid-evolution/blob/e88f247a3178ce4847c6700a28eef6ef32463691/packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts#L106](https://github.com/Anastasia-Labs/lucid-evolution/blob/e88f247a3178ce4847c6700a28eef6ef32463691/packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts#L106)
is not enough for some transactions.

Trying to submit the following tx:
[transaction.txt](https://github.com/user-attachments/files/17667435/transaction.txt)

resulted in the following error:
`Error: {"contents":{"contents":{"contents":{"era":"ShelleyBasedEraConway","error":["ConwayUtxowFailure (UtxoFailure (InsufficientCollateral (DeltaCoin 5000000) (Coin 6692501)))"],"kind":"ShelleyTxValidationError"},"tag":"TxValidationErrorInCardanoMode"},"tag":"TxCmdTxSubmitValidationError"},"tag":"TxSubmitFail"}`

**Comment by solidsnakedev** [comment]
you can increase it if needed `.complete({setCollateral: 6_000_000n});`

**Comment by a-osiecki** [comment]
is the option is not available for the `chain` method ?
