### ISSUE TITLE
Error with walletFromSeed function

### ISSUE THREAD

**Issue by golddydev** [Anastasia-Labs/lucid-evolution#55]
Hi, I am trying to convert `lucid` to `lucid-evolution`.
And now, I faced an issue with `walletFromSeed` function.

```typescript
import {
  generateSeedPhrase,
  walletFromSeed,
} from "@lucid-evolution/lucid";
const seed = generateSeedPhrase();
const { address } = walletFromSeed(seed);
```

This gives me error like this.
```typescript
Error {
  code: 'ERR_CRYPTO_HASH_FINALIZED',
  message: 'Digest already called',
}
```

**Comment by golddydev** [comment]
The funny thing is that if I use `generateSeedPhrase` from `lucid-cardano`, then it works all fine.
Working code
```typescript
import {
  walletFromSeed,
} from "@lucid-evolution/lucid";
import {
  generateSeedPhrase,
} from "lucid-cardano";
const seed = generateSeedPhrase();
const { address } = walletFromSeed(seed);
```

When I see both libraries code, the only difference is that `Sha256` function they use.

`lucid-cardano` uses `"https://deno.land/std@0.153.0/hash/sha256.ts"`,
`lucid-evolution` uses this approach.
```
import { createHash } from "node:crypto";
const Sha256 = createHash("sha256");
```

**Comment by golddydev** [comment]
This issue happens, because `hasher` does not reset, after you finalize the hasher using `digest`.
The possible way to fix is 
* Create hasher instance every time you need.
* Use hasher's `copy` method.

**Comment by solidsnakedev** [comment]
fixed https://github.com/Anastasia-Labs/lucid-evolution/pull/63

**Comment by golddydev** [comment]
Great
