### ISSUE TITLE
Does lucid-evolution support withdraw function?

### ISSUE THREAD

**Issue by golddydev** [Anastasia-Labs/lucid-evolution#58]
I am trying to build transaction to withdraw from stake address.
But I don't see any for this.
I only see the one which allows me to attach `withdrawal validator`.

**Comment by golddydev** [comment]
Great, :+1: 
Hope it is coming soon.

**Comment by solidsnakedev** [comment]
Give it a try; the withdrawal module has been added.

**Comment by golddydev** [comment]
Thank you for the update.

**Comment by solidsnakedev** [comment]
Closing this, let us know if you have any issues
