### ISSUE TITLE
Selecting Utxos issue.

### ISSUE THREAD

**Issue by golddydev** [Anastasia-Labs/lucid-evolution#59]
When we build tx using `lucid-evolution`, it selects all `utxos` in wallet as `inputs`. 
(NOT the only `utxos` to cover `outputs`)

I checked the code myself, and found this part, and I think this part is handling selecting `utxos` just enough to cover `outputs`

> [packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts](https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts#L99)

```typescript
config.txBuilder.select_utxos(
  CML.CoinSelectionStrategyCIP2.LargestFirst,
);
```

But, when it comes to reality, it doesn't work.

**Comment by solidsnakedev** [comment]
have you tried the latest version, I think this is issue is already fixed https://github.com/Anastasia-Labs/lucid-evolution/pull/119
